name: Do GitHub Release

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ github.ref_name }}
          noVersionBumpBehavior: patch

      - name: Create Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false
          excludeTypes: build,docs,style
          includeInvalidCommits: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Update major version tag
        uses: cdqag/update-majorver@v1
        with:
          static_major_version: ${{ steps.semver.outputs.nextMajor }}
