name: Docker Bake

on:
  workflow_call:
    inputs:
      docker-user:
        type: string
        description: 'Docker Hub username'
        required: true

    secrets:
      docker-pat:
        description: 'Docker Hub Personal Access Token'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ github.ref_name }}
          noNewCommitBehavior: current
          noVersionBumpBehavior: patch

      - if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
        name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker-user }}
          password: ${{ secrets.docker-pat }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set envs
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "APP_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "VERSION=${{ steps.semver.outputs.next }}" >> $GITHUB_ENV
          echo "DOCKER_USER=${{ inputs.docker-user }}" >> $GITHUB_ENV
          echo "DOCKER_BUILD_CHECKS_ANNOTATIONS=false" >> $GITHUB_ENV
          echo "DOCKER_BUILD_SUMMARY=false" >> $GITHUB_ENV
          echo "DOCKER_BUILD_RECORD_UPLOAD=false" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/bake-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}

      - if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
        name: Create Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false
          excludeTypes: build,docs,style
          excludeScopes: deploy,version
          includeInvalidCommits: true
  
      - if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
        name: Make GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
